- name: Clients
  jdbcTemplateName: jdbcTemplate
  visualizations:
   - id: DeviceTypeCount
     type: pie
     dataTransfomerClass: com.foo.MyClass
     sql: "select client_type, count(client_type) from clients_activity  where client_status='active' group by client_type"
     dataPushFrequencyInSeconds: 2
     disableDatabasePolling: true
     scaleInstances: 2
   - id: DeviceUsageTrend
     type: pie
     dataTransfomerClass: com.foo.MyClass
     sql: "select client_type, count(client_type) from clients_activity  where client_status='active' group by client_type"
     dataPushFrequencyInSeconds: 2
     disableDatabasePolling: true
     scaleInstances: 2









