- name: Clients
  jdbcTemplateName: jdbcTemplate
  visualizations:
   - id: DeviceTypeCount
     type: pie
     sql: "select client_type, count(client_type) from clients_activity  where client_status='active' group by client_type"
     dbPushEnabled: true

   - id: SecondOne
     type: pie
     sql: "select client_type, avg(memory_utilization) from clients_activity  where client_status='active' group by client_type"
     staleDataNoMoreThanSeconds: 2
     dbPushEnabled: false









